import type {
  Agent,
  AgentCategory,
  AgentCategoryInfo,
  PlatformStat,
  UserStats,
  Workflow,
} from "@/types/agent";

export const agentCategories: AgentCategoryInfo[] = [
  {
    id: "research",
    label: "Research",
    icon: "🔍",
    description: "Market research, competitor analysis, data gathering",
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "writing",
    label: "Writing",
    icon: "✍️",
    description: "Copywriting, blog posts, scripts, content creation",
    color: "from-pink-500 to-rose-600",
  },
  {
    id: "coding",
    label: "Coding",
    icon: "⚡",
    description: "Build apps, fix bugs, write tests, code review",
    color: "from-emerald-500 to-teal-600",
  },
  {
    id: "design",
    label: "Design",
    icon: "🎨",
    description: "UI/UX, mockups, brand assets, illustrations",
    color: "from-orange-500 to-amber-600",
  },
  {
    id: "marketing",
    label: "Marketing",
    icon: "📣",
    description: "Campaigns, social media, SEO, growth strategy",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "data",
    label: "Data",
    icon: "📊",
    description: "Analysis, visualization, ML models, insights",
    color: "from-indigo-500 to-violet-600",
  },
  {
    id: "automation",
    label: "Automation",
    icon: "🤖",
    description: "Workflows, integrations, RPA, scheduling",
    color: "from-slate-500 to-gray-700",
  },
  {
    id: "qa",
    label: "QA",
    icon: "🧪",
    description: "Testing, security audit, performance, validation",
    color: "from-red-500 to-rose-700",
  },
];

export const agents: Agent[] = [
  {
    id: "research-pro",
    name: "Scout",
    description: "Deep market research & competitor intelligence agent",
    longDescription:
      "Scout digs through 50+ data sources in parallel — news, social signals, SEC filings, app reviews — and synthesizes a strategy-grade briefing you can act on today.",
    category: "research",
    provider: "AgentGrid Labs",
    icon: "🔍",
    gradient: "from-violet-500 to-purple-600",
    rating: 4.9,
    reviews: 1284,
    hires: 18432,
    pricePerTask: 0.45,
    avgResponseTime: "12s",
    successRate: 98.2,
    tags: ["market-research", "competitors", "trends", "briefings"],
    capabilities: [
      "Multi-source synthesis",
      "Trend detection",
      "Competitor benchmarks",
      "Executive briefings",
    ],
    status: "active",
    featured: true,
  },
  {
    id: "copy-writer",
    name: "Quill",
    description: "Brand-voice copywriter for ads, blogs & emails",
    longDescription:
      "Quill matches your tone of voice from 3 sample assets and ships on-brand copy for any channel in seconds. Built-in A/B variant generation and conversion-focused hooks.",
    category: "writing",
    provider: "Verse AI",
    icon: "✍️",
    gradient: "from-pink-500 to-rose-600",
    rating: 4.8,
    reviews: 2104,
    hires: 32890,
    pricePerTask: 0.18,
    avgResponseTime: "6s",
    successRate: 96.7,
    tags: ["copywriting", "brand-voice", "ads", "email"],
    capabilities: [
      "Voice cloning",
      "A/B variant generation",
      "Hook engineering",
      "Channel adaptation",
    ],
    status: "active",
    featured: true,
  },
  {
    id: "code-architect",
    name: "Forge",
    description: "Full-stack engineer — ships production-ready code",
    longDescription:
      "Forge plans the architecture, writes the code, adds tests, and opens a PR. Specializes in Next.js, TypeScript, and Prisma. Knows when to ask before doing.",
    category: "coding",
    provider: "AgentGrid Labs",
    icon: "⚡",
    gradient: "from-emerald-500 to-teal-600",
    rating: 4.9,
    reviews: 3521,
    hires: 41200,
    pricePerTask: 1.25,
    avgResponseTime: "45s",
    successRate: 94.5,
    tags: ["typescript", "nextjs", "prisma", "tests"],
    capabilities: [
      "Feature implementation",
      "Bug fixing",
      "Test generation",
      "Code review",
    ],
    status: "active",
    featured: true,
  },
  {
    id: "design-studio",
    name: "Canvas",
    description: "Visual designer — UI mockups, brand kits & assets",
    longDescription:
      "Canvas takes a brief and returns pixel-perfect mockups in your design system. Generates brand kits, color palettes, icons, and exports to Figma.",
    category: "design",
    provider: "Pixelforge",
    icon: "🎨",
    gradient: "from-orange-500 to-amber-600",
    rating: 4.7,
    reviews: 892,
    hires: 12450,
    pricePerTask: 0.85,
    avgResponseTime: "30s",
    successRate: 92.1,
    tags: ["ui", "branding", "mockups", "figma"],
    capabilities: ["UI mockups", "Brand kits", "Color systems", "Icon sets"],
    status: "idle",
    featured: true,
  },
  {
    id: "growth-marketer",
    name: "Boost",
    description: "Growth marketer — campaigns, SEO & viral hooks",
    longDescription:
      "Boost plans full-funnel campaigns, writes the creative, schedules the posts, and tracks attribution. Knows the 2026 algorithm quirks on every major platform.",
    category: "marketing",
    provider: "Reach Labs",
    icon: "📣",
    gradient: "from-cyan-500 to-blue-500",
    rating: 4.6,
    reviews: 612,
    hires: 8200,
    pricePerTask: 0.65,
    avgResponseTime: "20s",
    successRate: 89.4,
    tags: ["growth", "seo", "social", "campaigns"],
    capabilities: [
      "Funnel planning",
      "SEO content briefs",
      "Social calendars",
      "Attribution tracking",
    ],
    status: "active",
  },
  {
    id: "data-scientist",
    name: "Insight",
    description: "Data scientist — analysis, dashboards & ML models",
    longDescription:
      "Insight connects to your warehouse, cleans the data, builds the dashboards, and ships a Jupyter notebook explaining every decision. Trained on pandas, DuckDB, and scikit-learn.",
    category: "data",
    provider: "Numerai",
    icon: "📊",
    gradient: "from-indigo-500 to-violet-600",
    rating: 4.8,
    reviews: 421,
    hires: 5100,
    pricePerTask: 0.95,
    avgResponseTime: "60s",
    successRate: 91.7,
    tags: ["analysis", "dashboards", "ml", "notebooks"],
    capabilities: [
      "Data cleaning",
      "Dashboard design",
      "ML modeling",
      "Notebook delivery",
    ],
    status: "active",
  },
  {
    id: "automation-engineer",
    name: "Link",
    description: "Automation engineer — wires up your tool stack",
    longDescription:
      "Link reads your requirements and builds the integration — webhooks, cron jobs, queue workers. Ships with monitoring and retries baked in.",
    category: "automation",
    provider: "Loop Systems",
    icon: "🤖",
    gradient: "from-slate-500 to-gray-700",
    rating: 4.7,
    reviews: 287,
    hires: 3900,
    pricePerTask: 0.55,
    avgResponseTime: "25s",
    successRate: 93.2,
    tags: ["integrations", "webhooks", "cron", "workflows"],
    capabilities: [
      "Webhook setup",
      "Cron scheduling",
      "Queue workers",
      "Monitoring",
    ],
    status: "active",
  },
  {
    id: "qa-engineer",
    name: "Sentinel",
    description: "QA engineer — tests, security & perf audits",
    longDescription:
      "Sentinel runs end-to-end tests, fuzzes your APIs, scans for CVEs, and produces a triage-ready report. CI/CD ready out of the box.",
    category: "qa",
    provider: "AgentGrid Labs",
    icon: "🧪",
    gradient: "from-red-500 to-rose-700",
    rating: 4.9,
    reviews: 178,
    hires: 2200,
    pricePerTask: 0.75,
    avgResponseTime: "40s",
    successRate: 97.4,
    tags: ["testing", "security", "performance", "ci-cd"],
    capabilities: [
      "E2E test suites",
      "Security scans",
      "Performance audits",
      "CI/CD setup",
    ],
    status: "idle",
  },
  {
    id: "trend-scout",
    name: "Pulse",
    description: "Real-time trend scout for social & news",
    longDescription:
      "Pulse monitors X, Reddit, TikTok, Hacker News, and 30+ niche sources 24/7. Sends you a daily digest of what's about to break in your space.",
    category: "research",
    provider: "Signal Co.",
    icon: "📡",
    gradient: "from-fuchsia-500 to-purple-600",
    rating: 4.5,
    reviews: 234,
    hires: 1800,
    pricePerTask: 0.35,
    avgResponseTime: "8s",
    successRate: 88.9,
    tags: ["trends", "social", "monitoring"],
    capabilities: [
      "Real-time monitoring",
      "Daily digests",
      "Anomaly alerts",
      "Niche sources",
    ],
    status: "active",
  },
  {
    id: "script-writer",
    name: "Storyboard",
    description: "Video script writer for YouTube & reels",
    longDescription:
      "Storyboard writes hooks that retain. Drops in B-roll cues, beat shifts, and CTA. Knows the 2026 retention curve on YouTube and TikTok.",
    category: "writing",
    provider: "Reel Studio",
    icon: "🎬",
    gradient: "from-rose-500 to-red-600",
    rating: 4.6,
    reviews: 412,
    hires: 6700,
    pricePerTask: 0.4,
    avgResponseTime: "15s",
    successRate: 90.8,
    tags: ["scripts", "video", "youtube", "tiktok"],
    capabilities: ["Hook writing", "B-roll cues", "CTA design", "Retention edits"],
    status: "active",
  },
  {
    id: "frontend-dev",
    name: "Pixel",
    description: "Frontend specialist — React, Tailwind, animations",
    longDescription:
      "Pixel ships pixel-perfect components from a Figma frame or a screenshot. Knows shadcn/ui inside-out and never ships a layout that breaks on mobile.",
    category: "coding",
    provider: "Verse AI",
    icon: "🎨",
    gradient: "from-teal-500 to-emerald-600",
    rating: 4.8,
    reviews: 1102,
    hires: 14200,
    pricePerTask: 0.9,
    avgResponseTime: "35s",
    successRate: 95.3,
    tags: ["react", "tailwind", "shadcn", "animations"],
    capabilities: [
      "Component builds",
      "Responsive layouts",
      "Animation polish",
      "Figma → code",
    ],
    status: "active",
  },
  {
    id: "brand-strategist",
    name: "Atelier",
    description: "Brand strategist — positioning, voice & identity",
    longDescription:
      "Atelier runs positioning workshops in natural language, drafts your manifesto, and stress-tests your messaging against competitors. Used by 200+ early-stage YC founders.",
    category: "design",
    provider: "Studio Mono",
    icon: "✨",
    gradient: "from-amber-500 to-orange-600",
    rating: 4.7,
    reviews: 156,
    hires: 1400,
    pricePerTask: 1.1,
    avgResponseTime: "50s",
    successRate: 93.0,
    tags: ["branding", "positioning", "identity"],
    capabilities: [
      "Positioning workshops",
      "Manifesto drafting",
      "Messaging audits",
      "Voice guides",
    ],
    status: "idle",
  },
];

export const platformStats: PlatformStat[] = [
  {
    label: "Active Agents",
    value: "2,847",
    change: "+12.3%",
    trend: "up",
    icon: "Bot",
  },
  {
    label: "Tasks Executed",
    value: "4.2M",
    change: "+38.1%",
    trend: "up",
    icon: "Zap",
  },
  {
    label: "Avg Cost / Task",
    value: "$0.42",
    change: "-8.5%",
    trend: "down",
    icon: "DollarSign",
  },
  {
    label: "Success Rate",
    value: "94.7%",
    change: "+2.1%",
    trend: "up",
    icon: "CheckCircle",
  },
];

export const defaultUserStats: UserStats = {
  tasksThisMonth: 47,
  tasksLimit: 100,
  spendThisMonth: 32.4,
  spendLimit: 100,
  hiredAgents: [
    {
      agentId: "research-pro",
      hiredAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12),
      tasksCompleted: 18,
      tasksAssigned: 22,
      totalSpent: 8.1,
    },
    {
      agentId: "copy-writer",
      hiredAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7),
      tasksCompleted: 14,
      tasksAssigned: 15,
      totalSpent: 2.52,
    },
    {
      agentId: "code-architect",
      hiredAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3),
      tasksCompleted: 8,
      tasksAssigned: 10,
      totalSpent: 10.0,
    },
  ],
};

export const sampleWorkflow: Workflow = {
  id: "wf-demo",
  goal: "Build a SaaS landing page with competitor analysis, copy, design, and code",
  totalCost: 4.32,
  estimatedDurationMs: 180000,
  createdAt: new Date(),
  steps: [
    {
      id: "s1",
      order: 1,
      agentId: "research-pro",
      agentName: "Scout",
      agentIcon: "🔍",
      description: "Analyze top 5 competitors — positioning, pricing, messaging",
      output:
        "Briefing ready. Competitors: Linear, Notion, Vercel. Common gap: no API-first narrative.",
      status: "completed",
      cost: 0.9,
      durationMs: 14000,
    },
    {
      id: "s2",
      order: 2,
      agentId: "copy-writer",
      agentName: "Quill",
      agentIcon: "✍️",
      description: "Write hero, subhead, 3 feature blurbs, CTA",
      output:
        "Headline: 'Ship faster. Without the chaos.' Subhead + 3 features + CTA drafted in brand voice.",
      status: "completed",
      cost: 0.72,
      durationMs: 8000,
    },
    {
      id: "s3",
      order: 3,
      agentId: "design-studio",
      agentName: "Canvas",
      agentIcon: "🎨",
      description: "Produce hero mockup in brand palette",
      status: "running",
      cost: 0.85,
    },
    {
      id: "s4",
      order: 4,
      agentId: "frontend-dev",
      agentName: "Pixel",
      agentIcon: "🎨",
      description: "Implement mockup as responsive Next.js component",
      status: "pending",
      cost: 1.35,
    },
    {
      id: "s5",
      order: 5,
      agentId: "qa-engineer",
      agentName: "Sentinel",
      agentIcon: "🧪",
      description: "Run Lighthouse audit, E2E smoke test, ship to preview",
      status: "pending",
      cost: 0.5,
    },
  ],
};

export const exampleGoals = [
  "Build a SaaS landing page with competitor analysis, copy, design, and code",
  "Launch a 7-day Twitter growth campaign for my productivity app",
  "Audit my Next.js codebase for security issues and ship fixes",
  "Research the AI voice cloning market and write a 2000-word briefing",
  "Design a brand identity for a new coffee subscription startup",
];

export function getAgentsByCategory(category: AgentCategory | "all"): Agent[] {
  if (category === "all") return agents;
  return agents.filter((a) => a.category === category);
}

export function getAgentById(id: string): Agent | undefined {
  return agents.find((a) => a.id === id);
}

export function getFeaturedAgents(): Agent[] {
  return agents.filter((a) => a.featured);
}
